### ISSUE TITLE
Privately renamed items can be visible in the public API listing

### ISSUE THREAD

**Issue by repi** [cargo-public-api/cargo-public-api#145]
Ran into multiple problems regarding `use` statements on types (not not `pub use`) where the public API listing will be referring internal naming of the type within the module rather than the public type it is actually referring to. 

This input:

```rust
use macaw as internal_name_for_a_crate;
use macaw::Conformal3;
use macaw::Conformal3 as WeirdName;

pub fn test1(_transform: Conformal3) {}
pub fn test2(_transform: WeirdName) {}
pub fn test3(_transform: macaw::Conformal3) {}
pub fn test4(_transform: internal_name_for_a_crate::Conformal3) {}

pub enum Test {
    V1(Conformal3),
    V2(WeirdName),
    V3(macaw::Conformal3),
    V4(internal_name_for_a_crate::Conformal3),
}
```

Generates this output:

```rust
pub enum a2::Test
pub enum variant a2::Test::V1(Conformal3)
pub enum variant a2::Test::V2(WeirdName)
pub enum variant a2::Test::V3(macaw::Conformal3)
pub enum variant a2::Test::V4(internal_name_for_a_crate::Conformal3)
pub fn a2::test1(_transform: Conformal3)
pub fn a2::test2(_transform: WeirdName)
pub fn a2::test3(_transform: macaw::Conformal3)
pub fn a2::test4(_transform: internal_name_for_a_crate::Conformal3)
pub mod a2
```

Which I believe needs to be this to reflect what the public API actually is and not "leak" any internal naming within the crate module.

```rust
pub enum a2::Test
pub enum variant a2::Test::V1(macaw::Conformal3)
pub enum variant a2::Test::V2(macaw::Conformal3)
pub enum variant a2::Test::V3(macaw::Conformal3)
pub enum variant a2::Test::V4(macaw::Conformal3)
pub fn a2::test1(_transform: macaw::Conformal3)
pub fn a2::test2(_transform: macaw::Conformal3)
pub fn a2::test3(_transform: macaw::Conformal3)
pub fn a2::test4(_transform: macaw::Conformal3)
pub mod a2
```

Rustdoc HTML handles the the function output here correctly referring to all of them as `Conformal3` but all linking to the `macaw::Conformal3` docs page. I think in our case we would want it to be directly fully qualified names of  `macaw::Conformal3` everywhere where used.

In addition, even in the case of a single `use crate::type` can be problematic because one module could do that and use that `type` in a public API, and another module in the same crate could do `use crate2::type` and export another public API. So believe all imported used types need to be listed as fully qualified as `crate::<potential-path>::name` in the listing.

**Comment by Enselic** [comment]
According to my experimentation, it does not matter if the crate is external or not. Just adding

```rust
pub mod macaw {
    pub struct Conformal3;
}
```

to the top of your input, I get the exact same output as you (except also two extra items for `macaw`). Now, let's think about what kind of output we should expect. First, let's look at how rustdoc HTML prints this textually. For the enum, the rustdoc HTML looks like this:

```txt
pub enum Test {
    V1(Conformal3),
    V2(WeirdName),
    V3(Conformal3),
    V4(Conformal3),
}
```

And the function parameter types correspondingly looks the same.

In [general](https://github.com/Enselic/cargo-public-api#expected-output), we want to look like rustdoc HTML. But, sometimes we have good reason not to. Like here for example. It is actually better if the type is fully qualified, since otherwise  an API diff will not show any difference even if we change to a different `Conformal3`. But I'm not sure if it is worth the hassle to always fully qualify them.

All in all, I think acceptable output in this situation would be this:
```
pub enum a2::Test
pub enum variant a2::Test::V1(Conformal3)
pub enum variant a2::Test::V2(WeirdName)
pub enum variant a2::Test::V3(macaw::Conformal3)
pub enum variant a2::Test::V4(macaw::Conformal3)
pub fn a2::test1(_transform: Conformal3)
pub fn a2::test2(_transform: WeirdName)
pub fn a2::test3(_transform: macaw::Conformal3)
pub fn a2::test4(_transform: macaw::Conformal3)
pub mod a2
```

which is both
* close to rustdoc HTML output, and
* close to current output

I agree that the string `internal_name_for_a_crate` should not be exposed in the public API.

**Comment by repi** [comment]
thanks for a thoughtful and detailed response!
agree that that not expose the internal name is the highest priority of these.

I am still concerned about the renamed type name and not having all of them fully qualified.

For the renamed type, there is no line in the output indicating what it is, at all. that is not a definition of a public API as technically the typ could be anything. if one doesn't rename it in the public API listing, could one include some additional line similar to how it would look like if it was a public type, essentially something like:

`use macaw::Conformal3 as WeirdName` (note no `pub` here)

then one just by reading the public API listing would know what type it actually is.

**Comment by Enselic** [comment]
Ok, I agree that `WeirdName` should probably not be part of the listing either. In rustdoc HTML, if you click on `WeirdName`, you are taken to the page for `Conformal3`. But in our case, we should probably inline it directly, i.e. instead of `WeirdName` print `macaw::Conformal3`.

But I actually think the "real" problem is putting `WeirdName` in a public API in the first place :)

**Comment by repi** [comment]
Agree on both points :) 

But renames could also happen locally in a crate just to avoid some local conflict there, or to shorten / change type names just for that crate - which users generally don't see or care about.

**Comment by Enselic** [comment]
Here is a smaller way to reproduce:
```rust
// Could also be an external crate
pub mod external {
    pub struct S;
}

use external as renamed_external;
use external::S as RenamedS;

pub fn f1(_: renamed_external::S) {}
pub fn f2(_: RenamedS) {}
```

This will generate rustdoc JSON with parameter types that looks like this:

```json
{
    "kind": "resolved_path",
    "inner": {
        "name": "RenamedS",
        "id": "0:2:1615",
        "args": {
            "angle_bracketed": {
                "args": [],
                "bindings": []
            }
        }
    }
}
```
```json
{
    "kind": "resolved_path",
    "inner": {
        "name": "renamed_external::S",
        "id": "0:2:1615",
        "args": {
            "angle_bracketed": {
                "args": [],
                "bindings": []
            }
        }
    }
}
```
and the ID is the ID of the actual struct:
```json
"0:2:1615": {
    "id": "0:2:1615",
    "name": "S",
    "kind": "struct",
    ...
},
```

So I think what we should do is to not use the `"name"` of parameter types directly, but instead inline the items and resolve the full path to them. I doubt we can always inline such items though, because not always will it be privately renamed stuff.

But maybe someone wants to experiment with this. Since the problem in this issue only occurs when one puts privately renamed items in the public API (even if it is justifiable), I am removing the `high-prio` label.

The code to start poking around with is probably `render_resolved_path()` in `render.rs`. Maybe we need to pre-lookup the referenced item. See `pre_resolved_fields_for_item()` in `item_iterator.rs` for an another example where we do that.

Probably quite easy to get started with, so labelling as `good first issue`.

**Comment by Enselic** [comment]
Turns out I had to fix this for `impl` rendering, so I will take care of this issue.

WiP PR at https://github.com/Enselic/cargo-public-api/pull/156
