### ISSUE TITLE
Add option to force git checkouts

### ISSUE THREAD

**Issue by inikulin** [cargo-public-api/cargo-public-api#172]
I see from the `--diff-git-checkouts` option description that inability to do `git checkout` on a dirty tree is a feature. However, there are cases where it's not desirable. In our case rust build script produces some artefacts that are supposed to be checked in the repo. So, when the tool checks out the first commit and generates the docs the tree is not clean and the tools fails to checkout the second commit.

Would you accept a PR implementing an additional `--force-git-checkouts` option?

**Comment by Enselic** [comment]
Sounds good! I have needed this too at times, just never got around to implement it.

Maybe it even would make sense to assume that if the tree becomes dirty AFTER doing the initial checkout, then that MUST be caused by irrelevant changes. So maybe we should always add `--force` for the second `git checkout`.

But I think it is good to be a bit defensive and requirer users to opt in as a first step. It could be good to wait with being more smart until we are confident the manual opt-in works like we want.

Thanks for reporting and for the PR! (I  just left a review.)
