### ISSUE TITLE
Machine readable output for git diffs

### ISSUE THREAD

**Issue by inikulin** [cargo-public-api/cargo-public-api#176]
It would be nice to have a machine-readable output for the diffing tool (e.g. JSON), so upstream tools can consume it. E.g. having diffing running in CI and sending chat notifications about breaking changes.

**Comment by Enselic** [comment]
Thank you for this request. It does not sound completely unreasonable. But couldn't you simply send the output of `cargo public-api --diff...` to the chat? That output is meant to be easy to understand by humans.

It is not obvious to me what other use cases there are that would justify having machine-readable text-based diff output. But I am very interested in hearing about them.

Note that you can already now use the `public_api` library crate to get full fidelity diff info. Maybe we should move the git stuff of cargo-public-api into a library as well, so that it is easier to re-use by others.

**Comment by inikulin** [comment]
> But couldn't you simply send the output of cargo public-api --diff... to the chat? That output is meant to be easy to understand by humans.

You loose color highlighting both for syntax and diffs.

**Comment by Emilgardis** [comment]
if you can support ansi colors, using `--color always` could work

**Comment by inikulin** [comment]
Support of ansi colors depends on the medium to which the report will be re-transmitted, thus the request for the machine readable format, so highlighting can be implemented the way that destination understands.

**Comment by Emilgardis** [comment]
I think the easiest solution for everyone in regards to having colorized output for further processing is for you to consume  `public-api`

i.e

https://github.com/Enselic/cargo-public-api/blob/6ddaceccb35872169e7f442a21e085fc4184346a/public-api/examples/diff_public_api.rs

and instead of printing with `{:#?}` customize and print https://github.com/Enselic/cargo-public-api/blob/6ddaceccb35872169e7f442a21e085fc4184346a/public-api/src/diff.rs#L30-L44 as you see fit, see https://github.com/Enselic/cargo-public-api/blob/6ddaceccb35872169e7f442a21e085fc4184346a/cargo-public-api/src/plain.rs#L23 for how `cargo-public-api` does it

**Comment by inikulin** [comment]
@Emilgardis Thank you, sgtm. Closing.
