### ISSUE TITLE
Inline impl not fully qualified? 

### ISSUE THREAD

**Issue by SUPERCILEX** [cargo-public-api/cargo-public-api#204]
https://github.com/SUPERCILEX/ftzz/blob/4c1e4d97d3f4a8b48f0f4396c784beaac49e8618/api.golden#L36

It looks like methods such as `fn foo(a: &mut impl Type)` don't have their `Type` fully qualified.

**Comment by Enselic** [comment]
Thank you for reporting 🙏 

It works if the trait belongs to the root crate:

```rust
pub trait T {}
pub fn f(_: impl T) {}
```

```
pub mod api_test
pub trait api_test::T
pub fn api_test::f(impl api_test::T)
```

What you are seeing is a variant of https://github.com/Enselic/cargo-public-api/issues/103

Coincidentally, I merged a workaround for that yesterday: https://github.com/Enselic/cargo-public-api/pull/185

Now that you (too) raised this issue, I plan on making a new release sooner rather than later, probably within a few days

We can keep this issue open until then so it is easier for others who have the same question to find this discussion

**Comment by SUPERCILEX** [comment]
Awesome, thanks!

**Comment by Enselic** [comment]
https://github.com/Enselic/cargo-public-api/releases/tag/v0.23.0 has been released

The workaround is not perfect, because internal paths can be used, but I think it is better than nothing. Unsure if it is worth to put a lot of effort into working around the limitations. Seems to me that it is better to put effort into solving the issue upstream.

I'm considering to add an opt-out flag if users turn out to think the workaround is too buggy. We'll see.

**Comment by SUPERCILEX** [comment]
Sounds good. Just to confirm, the upstream issue is https://github.com/rust-lang/rust/issues/99513?

**Comment by Enselic** [comment]
Yes that is one example, another example is https://github.com/rust-lang/rust/issues/101059
