### ISSUE TITLE
rustdoc-json: add support for binaries

### ISSUE THREAD

**Issue by dimpolo** [cargo-public-api/cargo-public-api#245]
Currently rustdoc-json uncoditionallly passes `--lib`. 
This causes the following error on binary only crates:
```shell
error: no library targets found in package `...`
```

I'm not sure what a nice interface would look like here, so I though I'd open this issue to discuss :)

One idea I had was to change the `Builder::package` parameter from a `impl AsRef<str>` to a

```rust
enum Package<T: AsRef<str>> {
    Bin(T),
    Lib(T),
}
```

**Comment by Emilgardis** [comment]
What use case do you have in mind for documenting a binary package?

Afaik, the public api of a binary is non-existant, it doesn't have a public api

**Comment by Enselic** [comment]
I agree that it is tricky to see a use-case for binary packages for `public-api`/`cargo-public-api`, but for the use case of `rustdoc-json` I think it makes sense? Since you can generate HTML docs for a binary crate with `cargo doc` I think it makes sense to also be able to generate rustdoc JSON for a binary crate with `rustdoc-json`.

It is possible to generate rustdoc HTML for many targets at once:

```console
$ cargo +nightly doc -p public-api --example diff_public_api --example list_public_api
```

but with rustdoc JSON it does not seem to work since we use `rustdoc` flags:

```console
$ cargo +nightly rustdoc -p public-api --example diff_public_api --example list_public_api -- -Z unstable-options --output-format json 
error: extra arguments to `rustdoc` can only be passed to one target, consider filtering
the package by passing, e.g., `--lib` or `--bin NAME` to specify a single target
```

so I think our API need/should reflect that, i.e. we only allow to select one target per "build".

I'm a bit confused about the terminology here. It seems to me like "lib" and "bin" are two different so called "targets". So in the new API we could add Builder::target(). BUT, we already have `target`, for the target triplet. Maybe we should have called our current `target()` `target_triple()`? :thinking: 

I consider it important to get this right, so if we need to go through a deprecation cycle to be able to have good long-term names, I think it will be worth it.

For a given package there can be only one lib but many bins, so maybe the following is something we could go with?

```rust
enum Target<T: AsRef<str>> {
    Bin(T),
    Lib,
}
```

Let's continue experimenting and discussing this before we make a final decision.

@dimpolo Just a note: I plan to make a release of cargo-public-api shortly, but we can make another release one day later if we want, so don't interpret me making a release as if it will take a long time to make a release after we have figured out what to do here. It is not uncommon for this project to make several releases per week :)

**Comment by Emilgardis** [comment]
I agree, rustdoc json can be used for more stuff than public-api, so we should support it.


I think I prefer

```rust
#[derive(Default)]
enum Target<T> {
    #[default]
    Lib,
    Bin(T),
    Example(T),
    Test(T),
    Bench(T),
}
```

and having the builder setter be `package_target()`

some examples

```
-p foo --bin bar
->
Builder::default().package("foo").package_target(Target::Bin("bar"))

--example foo
->
Builder::default().package_target(Target::Example("foo"))

-p my_crate
->
Builder::default().package("my_crate") # and default() gives `package_target = Target::Lib`
```

the field should be defaulted to `--lib` (this is not how rustdoc does it, but I think it's what makes the most sense, you most likely want the rustdoc-json for a library).

**Comment by Emilgardis** [comment]
having it be named "package target" reflects what it actually signifies I think

**Comment by dimpolo** [comment]
This all seems very reasonable and certainly covers all my use cases.
I'll get working on a PR :)
