### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by epage** [cargo-public-api/cargo-public-api#3]
I was just wondering where we stood on collaboration.  In https://github.com/crate-ci/cargo-crate-api/issues/18 it sounded like there was interest though it looks like development has continued here, so unsure if that was a misunderstanding.

**Comment by Enselic** [comment]
Thank you for asking! After writing that, I investigated the project more in depth, and (perhaps wrongly) concluded that `cargo-crate-api` is looking to cover more advanced use cases than my project. Because of that, it has significantly more code and dependencies, and a more complicated CLI.

I'm a fan of minimalism. I want to be able to go to any crate, just type `cargo public-api`, and get all public items of the crate listed in text form, one line per item. One line per item is important, because I want to be able to diff public APIs across versions.

I did try to understand the code in `cargo-crate-api `, but felt lost. Granted, I did not spend enormous amounts of time on it, but I took a serious shot at it. Since I already had started my project, it was a much lower barrier for me to keep working on that tool, however. That seemed to me to be the fastest way to get the tool that I want to get. And spare time is a limited resource. Note: My project is far from done still.

However, I do want to point out that we still benefit from each others project. For example, while working on my tool, I discovered and reported https://github.com/rust-lang/rust/issues/92945, which seemingly will be fixed soon.  `cargo-crate-api` will certainly benefit from that bug getting fixed.

I also hope that we can continue collaborating when it makes sense! Feel free to ping me about any topic related to our projects and to rustdoc JSON in general.

Looking forward to hear your thoughts on this.

**Comment by epage** [comment]
If nothing else, I think there is room to collaborate on `crate-api` as its intended to be an abstraction over rustdoc.  The `cargo-breaking` folks feel that they want to go a different direction with the CLI as well but saw value in working together on `crate-api`.

Maybe I'm biased but if you are interested in showing the API and diffing it, I feel like collaborating on the CLI as well would be useful.  Besides any CLI beautification, the main extra dependency / functionality in `cargo-crate-api` is for built-in diffing.  While diffing the output of a public API can offer some information for a user, it will be limited because
- It can't ignore non-breaking changes (e.g. item gets renamed but a `use` aliases back to the old name)
- It is likely to catch too much (changes that have no impact).

**Comment by Enselic** [comment]
I would love it if we could share code for generating the rustdoc. My current bare-bones implementation does not support workspaced crates for example.

My near-term focus is on the `public_items` library itself, i.e. the parsing of the JSON. Once it is time to make the cargo wrapper robust, I will look into what it would take for us to share `crate-api`.

> It can't ignore non-breaking changes (e.g. item gets renamed but a use aliases back to the old name)

Good point. I did not consider that case before. I do however think it is edge-case enough to justify the simplicity of `cargo public-api`.

> It is likely to catch too much (changes that have no impact).

I can't think of of a change to a public item that does not affect the public API. Or do you mean things like renaming function parameters? Well, I guess you have a point there too. But I still think there is value in simplicity per se.

I want to stress again: I look forward to future collaboration, whatever that might end up being.

**Comment by epage** [comment]
> My near-term focus is on the public_items library itself, i.e. the parsing of the JSON. Once it is time to make the cargo wrapper robust, I will look into what it would take for us to share crate-api.

`crate-api` is meant for exposing the json in a way meaningful for processing.  All the cargo integration is in `cargo-crate-api`.

**Comment by Enselic** [comment]
Aha. I got the terminology backwards. Sorry about that.

I wonder if an abstraction over the rustdoc JSON is the best way forward though? The JSON is essentially an abstraction over the rustc internal representations of items. So then `crate-api` would be an abstraction over an abstraction.

It seems to me like it is better to put effort into getting the "first" level of abstraction right, i.e. the rustdoc JSON itself. More specifically: Figure out ways to make the rustdoc JSON easier to work with directly. Like this proposal for example: https://github.com/rust-lang/rust/issues/93524

**Comment by Enselic** [comment]
My last comment in this issue was not my brightest moment. The `public-api` crate has ended up as kind of an abstraction over rustdoc JSON.

Anyway, I'm not sure it makes sense to keep this open any longer? I'll go ahead and close it. Of course feel free to re-open if there is more to discuss.
