### ISSUE TITLE
Resolve `Self` to concrete type to avoid unnecessary diffs

### ISSUE THREAD

**Issue by sharkdp** [cargo-public-api/cargo-public-api#364]
In `bat`, we [recently changed](https://github.com/sharkdp/bat/commit/ec6e9c29ac11178854063f2177dde5392e430e2e) a custom `Default` implementation to an automatically derived one. The custom implementation used `Self` as a return type, the automatically derived implementation uses `ConcreteType`. As far as I can tell, this is never a breaking change (unless the type has been renamed at the same time)? Could changes in the API of this sort be automatically omitted?

```
> cargo public-api diff ec6e9c29ac^..ec6e9c29ac
Removed items from the public API
=================================
-pub fn bat::PagingMode::default() -> Self

Changed items in the public API
===============================
(none)

Added items to the public API
=============================
+pub fn bat::PagingMode::default() -> bat::PagingMode
```

**Comment by Enselic** [comment]
Hi David, and thank you for filing an enhancement request!

## Solution proposal

I think the best way to solve this would be to always resolve `Self` to the concrete type. This lib.rs:

```rust
pub struct S;

impl S {
    pub fn s() -> Self {
        S
    }
}
```

currently produce the following output:

```console
$ cargo public-api --omit blanket-impls --omit auto-trait-impls
pub mod lib
pub struct lib::S
impl lib::S
pub fn lib::S::s() -> Self
```

but the tool should resolve `Self` to `lib::S` in this case. Since that is in fact the actual, concrete public API.

*That way the unnecessary diffs would also go away.*

## Problems

The current rustdoc JSON output makes it tricky to resolve `Self` however, because all we get on this in **target/doc/lib.json** is:
```json
                    "output": {
                        "kind": "generic",
                        "inner": "Self"
                    },
```

It would be good if `rustdoc` could generate rustdoc JSON that makes it easy to resolve `Self`, such as having the `Id` of the resolved type. Unsure how doable that would be by `rustdoc`. I'll look into it! I noticed that rustdoc HTML does not do it.

Worst case we have to resolve it ourselves on a best-effort basis. Probably not super hard. Just good to not do unless we have to.

## How to inspect the raw rustdoc JSON

My preferred way to find the raw rustdoc JSON and inspect it is with `--verbose`:
```console
$ cargo public-api --verbose
Processing "/home/martin/src/lib/target/doc/lib.json"
...
```
and then use `bat` after auto-formatting the JSON:
```console
$ python3 -m json.tool "/home/martin/src/lib/target/doc/lib.json" | bat -ljson
```

**Comment by Enselic** [comment]
I have looked into this a bit. It is quite straightforward to make rustdoc resolve `Self` to the concrete type. Instead of interpreting `SelfTyAlias` as a generic parameter named `Self`, we resolve the `DefId` of the `alias_to` field. See [this diff](https://github.com/rust-lang/rust/compare/master...Enselic:rust:resolve-self).

But `SelfTyAlias` is not only used in function return types. It is also used for all variants of `self` parameters. To exemplify, take this lib code:

```rust
pub struct X;

impl X {
    pub fn x(self) -> Self {
        X
    }
}
```

With my patch to rustdoc, we get this output:

```console
$ cargo +resolve-self public-api -sss
pub mod lib
pub struct lib::X
impl lib::X
pub fn lib::X::x(self: lib::X) -> lib::X
```

But I don't think we also want to convert `self` to `self: lib::X`, right? With the current rustdoc infrastructure it seems hard to differentiate the cases, but I'm not even sure we'd want to. How would we justify doing it in one case but not the other? We could say that `-> Self` is more likely to cause a diff. But I find that unsatisfactory, because in principle the same problem applies in both cases. 🤔

**Comment by Emilgardis** [comment]
what does

```
pub struct X;

impl X {
    pub fn x(self: std::sync::Arc<Self>) -> Self {
        X
    }
}
```

resolve as in current and with the proposed change?

**Comment by Enselic** [comment]
Currently we do not resolve `Self` at all, so our current output is:

```console
$ cargo public-api -ss
pub mod lib
pub struct lib::X
impl lib::X
pub fn lib::X::x(self: alloc::sync::Arc<Self>) -> Self
```

With my rustdoc patch it becomes:

```console
$ cargo +resolve-self public-api -ss
pub mod lib
pub struct lib::X
impl lib::X
pub fn lib::X::x(self: alloc::sync::Arc<lib::X>) -> lib::X
```

(Sorry if you made a point which I missed.)

**Comment by sharkdp** [comment]
I should point out that this is really only a minor inconvenience, so it's probably not worth investing a lot of time into this problem, if it's not straightforward to resolve.

**Comment by Enselic** [comment]
No worries! I noticed this problem personally before you formalized it in an issue, so it is also for selfish reasons I am putting time into investigating this.

Another important point: If `-> Self` is used in a trait, we can't resolve it, but must keep it as `-> Self`:
```rust
pub trait SpecialClone {
    fn special_clone(&self) -> Self;
}
```

In conclusion, I currently don't see a nice and satisfying way of solving this problem. I think we have to live with this quirk. So I propose that we close this issue as "can't fix in a satisfactory way". We can of course re-open and re-consider if we get new insights.
