### ISSUE TITLE
Generic type information missing for items in paths

### ISSUE THREAD

**Issue by pragmatrix** [cargo-public-api/cargo-public-api#429]
Hi, I was trying to use cargo public-api diffs on skia-safe, which uses generic handle types for a lot of the exported types. Here is an minimum working example that explains the problem:

lib.rs:
```rust
pub struct Handle<T>(T);

pub type HU32 = Handle<u32>;

impl HU32 {
    pub fn get_u32() -> u32 {
        0
    }
}

```

results in

```rust
...
pub mod public_api_test
pub struct public_api_test::Handle<T>(_)
impl public_api_test::Handle<u32>
pub fn public_api_test::Handle::get_u32() -> u32
...
pub type public_api_test::HU32 = public_api_test::Handle<u32>
```

but I I think it the functions should be represented with their complete type signature:

```rust
...
pub fn public_api_test::Handle<u32>::get_u32() -> u32
```

Without that, a diff compares all functions of the generic type instead of only the concrete type.

**Comment by Enselic** [comment]
Thank you very much for taking the time to report this issue, and especially for your minimal reproducer. I have done some debugging, and the problem seems to be that for items in paths, generic parameters are ignored. Only the name of the item name is used if it is part of a path:

https://github.com/Enselic/cargo-public-api/blob/c1aac48db7796eee2fae308227370331b76fe7f6/public-api/src/render.rs#L249-L254

Clearly a somewhat big bug. I'm surprised it has not been noticed before. Instead of `output.push(token_fn(name.to_string()))` we probably need to call a higher-level rendering function like `fn token_stream()`, but refactor the code to avoid recursion.

**Comment by Enselic** [comment]
Oops, GitHub thought #430 was a fix. It wasn't...

**Comment by Enselic** [comment]
PR with fix: https://github.com/Enselic/cargo-public-api/pull/431

@pragmatrix If you want to test the fix already now on your real code you can do like this:
1. Check out my branch with the fix
2. Run the below command (but change `Cargo.toml` path of course)

```console
$ cargo run -- --manifest-path ~/src/lib/Cargo.toml --omit blanket-impls,auto-trait-impls,auto-derived-impls
pub mod lib
pub struct lib::Handle<T>(_)
impl lib::Handle<u32>
pub fn lib::Handle<u32>::get_u32() -> u32
pub type lib::HU32 = lib::Handle<u32>
```

**Comment by Enselic** [comment]
Fixed in https://crates.io/crates/cargo-public-api/0.31.0

**Comment by pragmatrix** [comment]
Thank you a lot! I have tried version 0.31.0 and the results were great. I am now able to diff the API surface of skia-safe as a pre-release check and immediately found some inconsistencies in the current master.
