### ISSUE TITLE
Installation instructions on README can be clarified

### ISSUE THREAD

**Issue by pramatias** [cargo-public-api/cargo-public-api#497]
Cargo fails to install on linux Ubuntu with the following error. My cargo version is 

$cargo --version
cargo 1.66.1

$ cargo +stable install cargo-public-api --locked
error: no such command: `+stable`

	Cargo does not handle `+toolchain` directives.
	Did you mean to invoke `cargo` through `rustup` instead?

**Comment by Emilgardis** [comment]
You need to have a nightly rust toolchain, or have rust installed with [rustup](https://rustup.rs/) instead of the cargo/rustc provided by ubuntu.

To fix this immediate error, `cargo install cargo-public-api --locked` should work, but you wouldn't be able to run `cargo public-api` as needed, since it's currently locked behind a nightly rustdoc

**Comment by Enselic** [comment]
@pramatias Would be great if you could propose what tweaks we should do to the README to clarify the requirements. Ideally the README should be clear enough so that these misunderstandings do not happen. At the same time they should be terse and easy to consume. It can be a tricky balance.
