### ISSUE TITLE
Add `--deny` flag for diffs in CI usage situations

### ISSUE THREAD

**Issue by HCastano** [cargo-public-api/cargo-public-api#63]
Hi there! Cool project 😄 

I'd like to use this as part of a CI pipeline but it doesn't look like there's any way to
programmatically check if something in the public API changed.

RustFmt has a [`--check` flag](https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server) which exits with `0` if the input would be formatted successfully
and `1` if it wouldn't be.

I think having a similar flag as part of this project would allow it to be used in the context
of CI.

**Comment by Enselic** [comment]
Thank you for the suggestion! Sounds good to me 👍 

Adding tests for it should be easy. I think we need three tests:
1. Test that `cargo public-api --diff-git-checkouts ... --check` returns 0 when there is no diff
2. Test that `cargo public-api --diff-git-checkouts ... --check` returns 1 when there is a diff
3. Test that only `cargo public-api --check` without `--diff-git-checkouts` is not allowed

Number 1. and 2. should be as easy as copy-pasting the code for
```
#[serial]
#[test]
fn diff_public_items() {
```
and making slight adjustments. 3. should be as easy as copy-pasting the code for
```
#[test]
fn long_help() {
```
and making slight adjustments.

**Comment by Enselic** [comment]
Before this is implemented you can still use `cargo public-api` in a CI pipeline by piping the output to a file and then checking that the output is equal to the empty diff:

```
Removed items from the public API
=================================
(none)

Changed items in the public API
===============================
(none)

Added items to the public API
=============================
(none)

```

**Comment by obi1kenobi** [comment]
Another happy `cargo-public-api` user here — thanks for making and maintaining this crate!

I also wanted a "`cargo test` but for semver problems" that I could use in CI, so I started building `cargo-semver-checks`: https://crates.io/crates/cargo-semver-checks

It's a complement for `cargo-public-api`, not a replacement. With `cargo-semver-checks`, you just run it and see if it passes or not, rather than digesting a printout of changes and manually deciding if they are okay. When it finds a semver violation, it will:
- point to specific files and line numbers where the violations occur
- print out a brief explanation of the rule
- link to the detailed explanation on the cargo semver reference page or other places
- link to the implementation of the rule in its GitHub repo, so you can easily report issues

Adding it to a GitHub Actions publish workflow is [a one-liner](https://github.com/obi1kenobi/cargo-semver-check/blob/main/.github/workflows/ci.yml#L158) with the corresponding GitHub Action: `obi1kenobi/cargo-semver-checks-action@v1`.

It's a brand new crate — only ~a week old at this point — so it doesn't check every semver rule yet, and it might be slow if you run it on a crate that's more than 100,000+ lines. But everything has to start somewhere 😅 I'm building it for fun and for use in my own crates, and I hope it might be useful to others too.

**Comment by Enselic** [comment]
@obi1kenobi Interesting! 

If you want to make your tool build rustdoc JSON for users rather than requiring the users to build rustdoc JSON themselves, you might find https://docs.rs/rustdoc-json/latest/rustdoc_json/ useful to start using in your project.

**Comment by obi1kenobi** [comment]
> @obi1kenobi Interesting!
> 
> If you want to make your tool build rustdoc JSON for users rather than requiring the users to build rustdoc JSON themselves, you might find https://docs.rs/rustdoc-json/latest/rustdoc_json/ useful to start using in your project.

Awesome, thanks for the suggestion — definitely going to be useful! I had just thrown together a GitHub Action to handle the rustdoc-building on CI, and it would be great to simplify the process especially for local use.
