### ISSUE TITLE
Check uncommitted working tree against last commit

### ISSUE THREAD

**Issue by LoganDark** [cargo-public-api/cargo-public-api#79]
I can't figure out if cargo-public-api already has this feature, but I would find it really helpful if I didn't have to commit my changes just to diff the public APIs.

**Comment by Enselic** [comment]
Thanks for the suggestion! Sounds good to me! I think we should wait with implementing until  https://github.com/Enselic/cargo-public-api/pull/72 has landed, because otherwise the risk for code conflicts is high.

Once the time is right, here are some pointers/proposals for how this could be implemented:

There is currently a function `fn collect_public_items_from_commit()` that takes a `commit: Option<&str>` where `None` means "current commit" and a `&str` is a commit SHA1. I think we should introduce an enum, maybe something like

```rust
enum Commit {
    Commit(&str),
    CurrentCommit,
    CurrentCommitStashed,
}
```

and change `fn collect_public_items_from_commit()` to handle that. `git` is good at refusing to do destructive changes, so it should be fine to do `git stash` and then `git stash pop` in code, I think. Akin to the current `git checkout SHA` code.

The CLI could be something like `cargo public-api --diff-local-changes-against-previous-commit`. Actually, terrible name... not sure what to call it exactly...

As for all features, we also needs to add tests. There is already a git repo that tests use that can be used for this. The repo lives in `target/tmp/cargo-public-api-test-repo`. The test code in `cargo-public-api-bin-tests.rs`. So a test should make some local modification to that git, then run the new CLI, and assert on that the correct diff is given. It should all happen programatically so that code coverage works. But it's easy to do in Rust, even though it may sound like a lot of work.

Shouldn't be super hard to do, so tentatively setting as "good first issue".

**Comment by LoganDark** [comment]
> Actually, terrible name... not sure what to call it exactly...

maybe `--diff-dirty` for the latest commit, and also `--diff-dirty-against <checkout>` to compare with a different ref, since uncommitted working tree is generally referred to as "dirty" (`cargo publish` also does this)

**Comment by Enselic** [comment]
`--diff-dirty` sounds good, at least as a preliminary name. For diffing worktree against an arbitrary commit, maybe we could use `--git-diff-checkouts <REF>`, i.e. with one commit instead of two? Or a special syntax, like `--git-diff-checkouts <REF> worktree`, but then people can't have branches that are called `worktree`, so I'm not a fan of that...

**Comment by douweschulte** [comment]
Good suggestion. I can add some suggestions for the naming:
Maybe the `--dif-dirty` could accept an optional argument to indicate to which commit the comparison should be made. With as default the last one. Or you could introduce `--git-diff-worktree <REF>` for this purpose.

**Comment by LoganDark** [comment]
> optional argument

Optional values (and variable numbers of arguments like @Enselic mentioned) require special care.

The first one is possible using explicit values only (`--flag=value` syntax, not `--flag value`). The second one is not possible.

I would only recommend the former.

[getargs](https://docs.rs/getargs/latest/getargs/) has finally released, so now I can point at the best practices <------- (except for lack of OsStr support which is impossible without unsafe code but entirely possible to implement yourself)

**Comment by Enselic** [comment]
Making `git stash`/`git stash pop` robust (restoring properly in case of failures) is actually probably quite tricky, so I'm removing the "good first issue" label for now. If we get that wrong, people will be at risk of losing work (or at least being at risk of it **appearing** to lose work ("where did my local changes go??")). (Personally I make tons of temporary commits, because I am always paranoid about losing work.)

Of the options discussed so far, my favourite CLI for this is `--diff-dirty` (same as `--diff-dirty HEAD`) and `--diff-dirty <commitish>` (but I am open to being convinced of other alternatives.)

**Comment by LoganDark** [comment]
> Of the options discussed so far, my favourite CLI for this is `--diff-dirty` (same as `--diff-dirty HEAD`) and `--diff-dirty <commitish>` (but I am open to being convinced of other alternatives.)

Since you seem to have missed my comment about them I would instead like to point you to the [`getargs` documentation on optional values](https://docs.rs/getargs/0.5.0/getargs/struct.Options.html#method.value_opt) which explains why `--diff-dirty` (with no value) and `--diff-dirty <arg>` cannot coexist in the same CLI.

It'll have to be `--diff-dirty` for no argument and `--diff-dirty=<arg>` for an argument if you want to combine them both into the same flag. :)

**Comment by Enselic** [comment]
Note that since a while back it is possible to diff the working tree against a published version of the crate. You do it like this:

    cargo public-api diff <version>

**Comment by Enselic** [comment]
Since diffing the working tree against
* a published crate version works
* a public API snapshot in CI

works, and since by my estimation that is the main use cases of diffing, and since I am not aware of any plans to implement this, I will close this as won't fix to keep the issue inbox small. It can always be re-opened if someone comes around that wants to implement and maintain this.
